#!/usr/bin/env python3

from sneks.config import SneksParser
import json

def main():
    args = SneksParser().parse_args()
    conf = args.sneks_config
    lines = []
    for k in conf:
        val = conf[k]
        if isinstance(val, (list, dict)):
            val = json.dumps(val, sort_keys=True)
        lines.append('export {}={}'.format(k, json.dumps(val)))
    print("\n".join(lines))

if __name__ == "__main__":
    main()
