#!/usr/bin/env python3

import json

from sneks.config import load_stack_info, SneksParser

def main():
    args = SneksParser().parse_args().sneks_config

    stack_info = load_stack_info()
    build_outputs = stack_info["build_stack_outputs"]
    deploy_stack_name = stack_info["deploy_stack_name"]
    build_stack_name = stack_info["build_stack_name"]

    variables = {
        'S3_BUCKET':build_outputs['ArtifactBucket'],
        'STATIC_BUCKET':build_outputs['StaticAssetBucket'],
        'AWS_PROFILE':args.get('AWS_PROFILE','default'),
        'AWS_REGION':args.get('AWS_REGION','us-east-1'),
        'STACK_NAME':deploy_stack_name,
        'BUILD_STACK_NAME':build_stack_name
    }
    if "BUILD_PARAMS" in args:
        variables["BUILD_PARAMS"] = json.dumps(args["BUILD_PARAMS"], sort_keys=True)
    for k in variables:
        print("export {}='{}'".format(k, variables[k]))

if __name__ == "__main__":
    main()
